# Database configuration
spring:
  datasource:
    url: jdbc:mysql://localhost/customer?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: ""
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

# Server configuration
server:
  port: 8080
  servlet:
    context-path:
